version: "3.9"

services:

  api:
    build: ./gptchatbot-api
    container_name: birgptchatbot-api
    ports:
      - "8010:8010"
    volumes:
      - ./gptchatbot-api:/app
    restart: always

  ui:
    build: ./gptchatbot-ui
    container_name: birgptchatbot-ui
    ports:
      - "8101:8101"
    volumes:
      - ./gptchatbot-ui:/app
    depends_on:
      - api
    restart: always
