# Generated by Django 5.2.7 on 2026-04-11 06:03

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='birdocument',
            name='file',
        ),
        migrations.AddField(
            model_name='birdocument',
            name='chunk_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='birdocument',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, null=True),
        ),
    ]
